version: 2.1

jobs:
  ci-build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build service
          command: |
            set -x
            bash ./ci/ci-build.sh

      - deploy:
          name: Push image to docker hub
          command: |
            set -x
            bash ./ci/ci-push.sh

  cd-k8s: 
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - run:
          name: Deploy app
          command: |
            set -x
            bash ./cd/deploy.sh


workflows:
  ci-cd:
    jobs:
      - ci-build

      - cd-approve:
          type: approval
          requires:
            - ci-build
      - cd-k8s:
          requires:
            - cd-approve